[project]
name = "spacemouse-ros2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "easyhid>=0.0.10",
    "pyspacemouse>=1.1.4",
]
